// Automatically generated by astro-icon
// 489bbbf92f76495a5ca6e96e2853761bfa7c2e1ea9d0db7b80760e8c5fd668fe

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "media/email"
		| "media/figma"
		| "media/github"
		| "media/twitter"
		| "media/wechat"
		| "sk/astro"
		| "sk/axurerp"
		| "sk/css3"
		| "sk/dira"
		| "sk/figma"
		| "sk/html"
		| "sk/javascript"
		| "sk/office"
		| "sk/photoshop"
		| "sk/react"
		| "sk/sass"
		| "sk/sketch"
		| "sk/tailwindcss"
		| "sk/typescript"
		| "sk/vue"
		| "sk/weixin"
		| "sk/xmind";
}